FROM ghcr.io/spack/windows-resource/mingw-w64:latest

RUN mkdir -p /opt/file/src /opt/file/bin
WORKDIR /opt/file/src

RUN curl -o file.tar.gz https://github.com/file/file/archive/refs/tags/FILE5_45.tar.gz &&\
  tar -oxf file.tar.gz

WORKDIR /opt/file/src/file

# Build file
RUN ./confgiure \
      --prefix=/opt/file \
      --host=x86_64-w64-mingw32 \
      --target=x86_64-w64-mingw32 \
      --disable-multilib \
      --enable-languages=c,c++ && \
    make -j4 && \
    make install
