on:
  workflow_call:


jobs:
  build-gpg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Fetch mingw artifact
        uses: actions/download-artifact@v3
        with:
            name: mingw-w64-image
            path: /tmp/images
      - name: Load image from artifact
        run: |
          docker load --input /tmp/images/mingw-w64.tar
      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfiles/gpg/Dockerfile.gpg
          load: true